### ISSUE TITLE
Not working with 2023.1.11f1

### ISSUE THREAD

**Issue by pastuh** [LavaGang/MelonLoader.Installer#15]
Testing v0.6.1 version
Game Type: Il2cpp
Game Arch: x64

Unity Version: 2021.3.25f1 - Works without any issues

Unity Version: 2023.1.11f1 - Game crash

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. 
Repeat 2 times:
at Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target (UInt32)
at Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase.get_Pointer()
at Il2CppInterop.Runtime.IL2CPP.Il2CppObjectBaseToPtr(Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase)
at Il2CppSystem.IO.StreamWriter..ctor(Il2CppSystem.IO.Stream)
at System.RuntimeMethodHandle. InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boole an, Boolean)
at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.o bject[], System.Globalization.CultureInfo)
at System.Reflection.Constructor Info. Invoke(System.Object[])
at MelonLoader.Support.Main.ConsoleCleaner()
at MelonLoader.Support.Main. Initialize(MelonLoader. ISupportModule_From)
at System.RuntimeMethodHandle. InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boole an, Boolean)
at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
at System.Reflection.MethodBase. Invoke(System.Object, System.Object[])
at MelonLoader.Support Module.LoadInterface (System.String)
at MelonLoader.SupportModule.Setup()
at MelonLoader.Core.Start()
at MelonLoader.NativeHost.NativeEntryPoint.Start()
```

**Comment by RinLovesYou** [comment]
This is the MelonLoader installer repo. Please go to the [MelonLoader](https://github.com/lavagang/melonloader) repo, open an issue, and include a full log
